spring:
  data:
    uri: mongodb://localhost:27017/studentdbsdstest
    database: studentdbsdstest

  security:
    oauth2:
      resourceserver:
        issuer-uri:  # OAuth2.0 provider URL
        jwk-set-uri: # URL to get JWKS keys

  server:
    port: # Port on which the application will run

  logging:
    level:
      root: info